export const cartMock = {
  __typename: 'Checkout',
  id:
    'Z2lkOi8vc2hvcGlmeS9DaGVja291dC8zMTkxYjU2YzM0YWU3M2FjYTJjZGUyYmRmNTQ2NGRhYT9rZXk9NTY2NGJjMzhiYmU2MmEyMWYzZTkzMGJhNmY5NDc1ZWM=',
  ready: true,
  requiresShipping: true,
  note: null,
  paymentDue: '135.00',
  paymentDueV2: {
    amount: '135.0',
    currencyCode: 'EUR',
    type: {
      name: 'MoneyV2',
      kind: 'OBJECT',
      fieldBaseTypes: { amount: 'Decimal', currencyCode: 'CurrencyCode' },
      implementsNode: false,
    },
  },
  webUrl:
    'https://wdkl-ocean.myshopify.com/7422733/checkouts/3191b56c34ae73aca2cde2bdf5464daa?key=5664bc38bbe62a21f3e930ba6f9475ec',
  orderStatusUrl: null,
  taxExempt: false,
  taxesIncluded: true,
  currencyCode: 'EUR',
  totalTax: '0.00',
  totalTaxV2: { amount: '0.0', currencyCode: 'EUR' },
  lineItemsSubtotalPrice: { amount: '135.0', currencyCode: 'EUR' },
  subtotalPrice: '135.00',
  subtotalPriceV2: { amount: '135.0', currencyCode: 'EUR' },
  totalPrice: '135.00',
  totalPriceV2: { amount: '135.0', currencyCode: 'EUR' },
  completedAt: null,
  createdAt: '2020-11-15T15:25:35Z',
  updatedAt: '2020-11-20T16:52:59Z',
  email: null,
  discountApplications: [],
  appliedGiftCards: [],
  shippingAddress: null,
  shippingLine: null,
  customAttributes: [],
  order: null,
  lineItems: [
    {
      id:
        'Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzMxMzY2ODM0MTkyNDczMD9jaGVja291dD0zMTkxYjU2YzM0YWU3M2FjYTJjZGUyYmRmNTQ2NGRhYQ==',
      title: 'ALLI One Piece - blue',
      variant: {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMTM2NjgzNDE5MjQ3Mw==',
        title: 'S/M',
        price: '135.00',
        priceV2: { amount: '135.0', currencyCode: 'EUR' },
        presentmentPrices: [
          {
            price: { amount: '135.0', currencyCode: 'EUR' },
            compareAtPrice: { amount: '165.0', currencyCode: 'EUR' },
            type: {
              name: 'ProductVariantPricePair',
              kind: 'OBJECT',
              fieldBaseTypes: { compareAtPrice: 'MoneyV2', price: 'MoneyV2' },
              implementsNode: false,
            },
            hasNextPage: false,
            hasPreviousPage: false,
            variableValues: {
              id:
                'Z2lkOi8vc2hvcGlmeS9DaGVja291dC8zMTkxYjU2YzM0YWU3M2FjYTJjZGUyYmRmNTQ2NGRhYT9rZXk9NTY2NGJjMzhiYmU2MmEyMWYzZTkzMGJhNmY5NDc1ZWM=',
            },
          },
        ],
        weight: 195,
        available: true,
        sku: 'WDLK202013-2',
        compareAtPrice: '165.00',
        compareAtPriceV2: { amount: '165.0', currencyCode: 'EUR' },
        image: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTM2OTQzNDU5MzY5ODU=',
          src:
            'https://cdn.shopify.com/s/files/1/0742/2733/products/155.jpg?v=1580458979',
          altText: null,
          type: {
            name: 'Image',
            kind: 'OBJECT',
            fieldBaseTypes: {
              altText: 'String',
              id: 'ID',
              originalSrc: 'URL',
              src: 'URL',
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: 'Size',
            value: 'S/M',
            type: {
              name: 'SelectedOption',
              kind: 'OBJECT',
              fieldBaseTypes: { name: 'String', value: 'String' },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: 'UnitPriceMeasurement',
            kind: 'OBJECT',
            fieldBaseTypes: {
              measuredType: 'UnitPriceMeasurementMeasuredType',
              quantityUnit: 'UnitPriceMeasurementMeasuredUnit',
              quantityValue: 'Float',
              referenceUnit: 'UnitPriceMeasurementMeasuredUnit',
              referenceValue: 'Int',
            },
            implementsNode: false,
          },
        },
        product: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ0MzQ1OTE1ODAyNDk=',
          handle: 'alli-one-piece-blue',
          type: {
            name: 'Product',
            kind: 'OBJECT',
            fieldBaseTypes: {
              availableForSale: 'Boolean',
              createdAt: 'DateTime',
              description: 'String',
              descriptionHtml: 'HTML',
              handle: 'String',
              id: 'ID',
              images: 'ImageConnection',
              onlineStoreUrl: 'URL',
              options: 'ProductOption',
              productType: 'String',
              publishedAt: 'DateTime',
              title: 'String',
              updatedAt: 'DateTime',
              variants: 'ProductVariantConnection',
              vendor: 'String',
            },
            implementsNode: true,
          },
        },
        type: {
          name: 'ProductVariant',
          kind: 'OBJECT',
          fieldBaseTypes: {
            availableForSale: 'Boolean',
            compareAtPrice: 'Money',
            compareAtPriceV2: 'MoneyV2',
            id: 'ID',
            image: 'Image',
            presentmentPrices: 'ProductVariantPricePairConnection',
            price: 'Money',
            priceV2: 'MoneyV2',
            product: 'Product',
            selectedOptions: 'SelectedOption',
            sku: 'String',
            title: 'String',
            unitPrice: 'MoneyV2',
            unitPriceMeasurement: 'UnitPriceMeasurement',
            weight: 'Float',
          },
          implementsNode: true,
        },
      },
      quantity: 1,
      customAttributes: [
        {
          key: 'slug',
          value: '/products/alli-one-piece-blue',
          type: {
            name: 'Attribute',
            kind: 'OBJECT',
            fieldBaseTypes: { key: 'String', value: 'String' },
            implementsNode: false,
          },
        },
      ],
      discountAllocations: [],
      type: {
        name: 'CheckoutLineItem',
        kind: 'OBJECT',
        fieldBaseTypes: {
          customAttributes: 'Attribute',
          discountAllocations: 'DiscountAllocation',
          id: 'ID',
          quantity: 'Int',
          title: 'String',
          variant: 'ProductVariant',
        },
        implementsNode: true,
      },
      hasNextPage: false,
      hasPreviousPage: false,
    },
  ],
  type: {
    name: 'Checkout',
    kind: 'OBJECT',
    fieldBaseTypes: {
      appliedGiftCards: 'AppliedGiftCard',
      completedAt: 'DateTime',
      createdAt: 'DateTime',
      currencyCode: 'CurrencyCode',
      customAttributes: 'Attribute',
      discountApplications: 'DiscountApplicationConnection',
      email: 'String',
      id: 'ID',
      lineItems: 'CheckoutLineItemConnection',
      lineItemsSubtotalPrice: 'MoneyV2',
      note: 'String',
      order: 'Order',
      orderStatusUrl: 'URL',
      paymentDue: 'Money',
      paymentDueV2: 'MoneyV2',
      ready: 'Boolean',
      requiresShipping: 'Boolean',
      shippingAddress: 'MailingAddress',
      shippingLine: 'ShippingRate',
      subtotalPrice: 'Money',
      subtotalPriceV2: 'MoneyV2',
      taxExempt: 'Boolean',
      taxesIncluded: 'Boolean',
      totalPrice: 'Money',
      totalPriceV2: 'MoneyV2',
      totalTax: 'Money',
      totalTaxV2: 'MoneyV2',
      updatedAt: 'DateTime',
      webUrl: 'URL',
    },
    implementsNode: true,
  },
};
