import { Token } from 'prismjs';

export const prismTokens = [
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '<',
            length: 1,
            greedy: false,
          },
          'pre',
        ],
        length: 4,
        greedy: false,
      },
      ' ',
      {
        type: 'attr-name',
        content: ['sx'],
        length: 2,
        greedy: false,
      },
      {
        type: 'script',
        content: [
          {
            type: 'script-punctuation',
            content: '=',
            alias: 'punctuation',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '{',
            length: 1,
            greedy: false,
          },
          {
            type: 'function',
            content: 'createStylesPre',
            length: 15,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '(',
            length: 1,
            greedy: false,
          },
          'props',
          {
            type: 'punctuation',
            content: '.',
            length: 1,
            greedy: false,
          },
          'size',
          {
            type: 'punctuation',
            content: ',',
            length: 1,
            greedy: false,
          },
          ' qt',
          {
            type: 'punctuation',
            content: ',',
            length: 1,
            greedy: false,
          },
          ' props',
          {
            type: 'punctuation',
            content: '.',
            length: 1,
            greedy: false,
          },
          'theme',
          {
            type: 'punctuation',
            content: ')',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '}',
            length: 1,
            greedy: false,
          },
        ],
        alias: 'language-javascript',
        length: 47,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 55,
    greedy: true,
  },
  '\n    ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '<',
            length: 1,
            greedy: false,
          },
          'code',
        ],
        length: 5,
        greedy: false,
      },
      ' ',
      {
        type: 'attr-name',
        content: ['sx'],
        length: 2,
        greedy: false,
      },
      {
        type: 'script',
        content: [
          {
            type: 'script-punctuation',
            content: '=',
            alias: 'punctuation',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '{',
            length: 1,
            greedy: false,
          },
          'stylesCode',
          {
            type: 'punctuation',
            content: '}',
            length: 1,
            greedy: false,
          },
        ],
        alias: 'language-javascript',
        length: 13,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 22,
    greedy: true,
  },
  '\n      ',
  {
    type: 'punctuation',
    content: '{',
    length: 1,
    greedy: false,
  },
  'tokens',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  {
    type: 'function',
    content: 'map',
    length: 3,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  'token',
  {
    type: 'operator',
    content: ':',
    length: 1,
    greedy: false,
  },
  ' Token ',
  {
    type: 'operator',
    content: '|',
    length: 1,
    greedy: false,
  },
  ' string',
  {
    type: 'punctuation',
    content: ',',
    length: 1,
    greedy: false,
  },
  ' i',
  {
    type: 'operator',
    content: ':',
    length: 1,
    greedy: false,
  },
  ' number',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  {
    type: 'operator',
    content: ':',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'constant',
    content: 'JSX',
    length: 3,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  {
    type: 'parameter',
    content: ['Element'],
    length: 7,
    greedy: false,
  },
  ' ',
  {
    type: 'operator',
    content: '=>',
    length: 2,
    greedy: false,
  },
  ' ',
  {
    type: 'punctuation',
    content: '{',
    length: 1,
    greedy: false,
  },
  '\n        console',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  {
    type: 'function',
    content: 'log',
    length: 3,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  'tokens',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: ';',
    length: 1,
    greedy: false,
  },
  '\n        ',
  {
    type: 'keyword',
    content: 'return',
    length: 6,
    greedy: false,
  },
  ' token',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  'type ',
  {
    type: 'operator',
    content: '?',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  '\n          Array',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  {
    type: 'function',
    content: 'isArray',
    length: 7,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  'token',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  'content',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'operator',
    content: '?',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  '\n            ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '<',
            length: 1,
            greedy: false,
          },
          {
            type: 'class-name',
            content: 'TokenList',
            length: 9,
            greedy: false,
          },
        ],
        length: 10,
        greedy: false,
      },
      ' ',
      {
        type: 'attr-name',
        content: ['content'],
        length: 7,
        greedy: false,
      },
      {
        type: 'script',
        content: [
          {
            type: 'script-punctuation',
            content: '=',
            alias: 'punctuation',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '{',
            length: 1,
            greedy: false,
          },
          'token',
          {
            type: 'punctuation',
            content: '.',
            length: 1,
            greedy: false,
          },
          'content',
          {
            type: 'punctuation',
            content: '}',
            length: 1,
            greedy: false,
          },
        ],
        alias: 'language-javascript',
        length: 16,
        greedy: false,
      },
      ' ',
      {
        type: 'attr-name',
        content: ['theme'],
        length: 5,
        greedy: false,
      },
      {
        type: 'script',
        content: [
          {
            type: 'script-punctuation',
            content: '=',
            alias: 'punctuation',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '{',
            length: 1,
            greedy: false,
          },
          'theme',
          {
            type: 'punctuation',
            content: '}',
            length: 1,
            greedy: false,
          },
        ],
        alias: 'language-javascript',
        length: 8,
        greedy: false,
      },
      ' ',
      {
        type: 'punctuation',
        content: '/>',
        length: 2,
        greedy: false,
      },
    ],
    length: 51,
    greedy: true,
  },
  '\n          ',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'operator',
    content: ':',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  '\n            ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '<',
            length: 1,
            greedy: false,
          },
          'span',
        ],
        length: 5,
        greedy: false,
      },
      ' ',
      {
        type: 'attr-name',
        content: ['sx'],
        length: 2,
        greedy: false,
      },
      {
        type: 'script',
        content: [
          {
            type: 'script-punctuation',
            content: '=',
            alias: 'punctuation',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '{',
            length: 1,
            greedy: false,
          },
          'theme',
          {
            type: 'punctuation',
            content: '.',
            length: 1,
            greedy: false,
          },
          {
            type: 'function',
            content: 'get',
            length: 3,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '(',
            length: 1,
            greedy: false,
          },
          'token',
          {
            type: 'punctuation',
            content: '.',
            length: 1,
            greedy: false,
          },
          'type',
          {
            type: 'punctuation',
            content: ')',
            length: 1,
            greedy: false,
          },
          {
            type: 'punctuation',
            content: '}',
            length: 1,
            greedy: false,
          },
        ],
        alias: 'language-javascript',
        length: 24,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 33,
    greedy: true,
  },
  '\n              ',
  {
    type: 'punctuation',
    content: '{',
    length: 1,
    greedy: false,
  },
  {
    type: 'keyword',
    content: 'typeof',
    length: 6,
    greedy: false,
  },
  ' token',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  'content ',
  {
    type: 'operator',
    content: '===',
    length: 3,
    greedy: false,
  },
  ' ',
  {
    type: 'string',
    content: "'string'",
    length: 8,
    greedy: true,
  },
  ' ',
  {
    type: 'operator',
    content: '&&',
    length: 2,
    greedy: false,
  },
  ' token',
  {
    type: 'punctuation',
    content: '.',
    length: 1,
    greedy: false,
  },
  'content',
  {
    type: 'punctuation',
    content: '}',
    length: 1,
    greedy: false,
  },
  '\n            ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '</',
            length: 2,
            greedy: false,
          },
          'span',
        ],
        length: 6,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 7,
    greedy: true,
  },
  '\n          ',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  '\n        ',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'operator',
    content: ':',
    length: 1,
    greedy: false,
  },
  ' ',
  {
    type: 'punctuation',
    content: '(',
    length: 1,
    greedy: false,
  },
  '\n          ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '<',
            length: 1,
            greedy: false,
          },
          'span',
        ],
        length: 5,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 6,
    greedy: true,
  },
  {
    type: 'punctuation',
    content: '{',
    length: 1,
    greedy: false,
  },
  'token',
  {
    type: 'punctuation',
    content: '}',
    length: 1,
    greedy: false,
  },
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '</',
            length: 2,
            greedy: false,
          },
          'span',
        ],
        length: 6,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 7,
    greedy: true,
  },
  '\n        ',
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: ';',
    length: 1,
    greedy: false,
  },
  '\n      ',
  {
    type: 'punctuation',
    content: '}',
    length: 1,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: ')',
    length: 1,
    greedy: false,
  },
  {
    type: 'punctuation',
    content: '}',
    length: 1,
    greedy: false,
  },
  '\n    ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '</',
            length: 2,
            greedy: false,
          },
          'code',
        ],
        length: 6,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 7,
    greedy: true,
  },
  '\n  ',
  {
    type: 'tag',
    content: [
      {
        type: 'tag',
        content: [
          {
            type: 'punctuation',
            content: '</',
            length: 2,
            greedy: false,
          },
          'pre',
        ],
        length: 5,
        greedy: false,
      },
      {
        type: 'punctuation',
        content: '>',
        length: 1,
        greedy: false,
      },
    ],
    length: 6,
    greedy: true,
  },
] as (string | Token)[];
