export enum Language {
  markup = 'markup',
  bash = 'bash',
  css = 'css',
  cssExtras = 'css-extras',
  clike = 'clike',
  javascript = 'javascript',
  jsx = 'jsx',
  jsExtras = 'js-extras',
  git = 'git',
  graphql = 'graphql',
  json = 'json',
  ocaml = 'ocaml',
  reason = 'reason',
  tsx = 'tsx',
  typescript = 'typescript',
  yaml = 'yaml',
}
